

class RandomGenerator{
	constructor(min, max){ 
		this.min = min;
		this.max = max;
		this.storage = 0;
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
	}
	generate(){
		var randomValue = Math.floor((Math.random() * this.max) + this.min);
		//make a random value between the minimum and maximum values
		return this.storage = randomValue;
		//and store the number into the storage from the constructor
	}
	getRange(){
		var rangeObj = {
			min: this.min,
			max: this.max
		};
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		return rangeObj;
		//returns a basic object literal
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.storage;
	}
}